<?php
	
	$dbHandler = new PTPL_DatabaseHandler;
	
	if( isset($_POST['activate']) ) {
		$activate = $_POST['activate'];
		$selectedMenu = $_POST['selectedMenu'];
		$defaultHeadings = trim($_POST['defaultHeadings']);
		if( isset($_POST['shuffleHeadings']) ){
			$shuffleHeadings = $_POST['shuffleHeadings'];
		} else {
			$shuffleHeadings = "no";
		}
		
		$selectedMenuData = "";
		if( $selectedMenu != 0 ) {
			$args = array(
				'post_type'              => 'nav_menu_item',
				'output'                 => ARRAY_A,
				'output_key'             => 'menu_order',
				'nopaging'               => true,
				'update_post_term_cache' => false );
			
			$menu_items = wp_get_nav_menu_items( $selectedMenu, $args );			
			foreach ( (array) $menu_items as $key => $menu_item ) {
				if( $menu_item->object == "category" ) {
					$selectedMenuData .= $menu_item->ID.";";
				}
			}
		}
		$dbHandler->saveAllSettings( $activate,$selectedMenu,trim($selectedMenuData, ";"),ptplProcessHeadings($defaultHeadings),$shuffleHeadings );
		$ptplSaved = true;
	}
	
	$ptplSettings = $dbHandler->getAllSettings();
	
	$ptplActive = $ptplSettings['active'];
	$ptplSelectedMenuID = $ptplSettings['menuid'];
	$ptplDefaultHeadings = $ptplSettings['headings'];
	$ptplShuffle = $ptplSettings['shuffled'];
	
	
	if( $ptplDefaultHeadings == "" ){
		$ptplDefaultHeadings = "You might also like\r\nRecommended for you\r\nMust reads";
	} else {
		$ptplDefaultHeadings = str_replace(';', "\r\n", $ptplDefaultHeadings);
	}
	
	ptplStyle ();
	ptplStartOutput ();
	ptplShowHeader ();
	
	if( $ptplSaved ) {
	?>
		<div class="menu_toggle" style="background:<?php echo ptplGetColor(); ?>;">Post Linker saved your settings!!!</div>
		<div class="toggle_content" style="background:<?php echo ptplGetColor(); ?>;"></div>
	<?php
	}
?>

	<div class="menu_toggle" style="background:<?php echo ptplGetColor(); ?>;">Important Things You Should Know Before Using</div>
	<div class="toggle_content" style="background:<?php echo ptplGetColor(); ?>;">
		<p>
			While creating Post Linker by <a href="http://pluginstalk.com" target="_blank">PluginsTalk.com</a> I've kept in mind one simple thing which is the following situation.<br />
			Suppose you are creating the "Recommended articles for you" section manually, then every time there is a page request for the article, it will show the <strong>same links, same heading & same links sequence</strong> because they were inserted manually.<br />
			<br />
			So the plugin does the same thing, it will create all the links automatically just once and show them always on every page request. No one would find that the links will be generated by Post linker or inserted manually.<br /><br />
			This means one more thing that suppose today post linker have added post links to your page and if you'll see the page a year later then also the same links will appear even if you've added new articles to your blog.
		</p>
		<hr />
		<p>
			Option to reset and regenerate links for any specific article (if you don't like links or you want to include new posts links) will be available in further updates of plugins.<br />
			The update of plugin also depends on you only. If you seriously like the plugin and want the plugin should have more & more cool features (which I already thought of, just hesitating in developing), then please do mail your feedback to <a href="http://pluginstalk.com/contact" target="_blank">sunil@pluginstalk.com</a> or <a href="http://wordpress.org/support/view/plugin-reviews/post-linker" target="_blank">write a review</a> about the plugin. I'll be very glad if you can <a href="http://www.pluginstalk.com/pluginstalk-needs-your-help" target="_blank">donate some amount</a> in appreciation for my plugins. All these things I want from you is just because I don't want to develop something, in which I don't get responses from my friends that use my plugins. I could have kept the plugin to myself also and enjoyed a lot. But I thought it would be helpful for you also. Remember that a <a href="http://pluginstalk.com/contact" target="_blank">response</a> cost nothing to you but have a lot of value for me.
		</p>
		<hr />
		<a href="http://pluginstalk.com" target="_blank"><h2>Visit PluginsTalk.com - World's Larget Upcoming Community For Web Browser Lovers</h2></a>
	</div>
	
	<form method="post">
	<div class="menu_toggle" style="background:<?php echo ptplGetColor(); ?>;">Activate/Deactivate Post Linker</div>
	<div class="toggle_content" style="background:<?php echo ptplGetColor(); ?>;">
		<p>
			<?php
				if( $ptplActive == "yes" ){
			?>
					<input type="radio" name="activate" value="yes" checked="checked" > Activate<br />
					<input type="radio" name="activate" value="no" > Deactivate
			<?php
				} else {
			?>
					<input type="radio" name="activate" value="yes"> Activate<br />
					<input type="radio" name="activate" value="no" checked="checked" > Deactivate
			<?php
				}
			?>
	  <h4>Note:-</h4>
			Deactivating the plugin from here will remove the shortcode [plinker] from your posts/pages or wherever you've used it. <br />Deactivating the plugin from the "Wordpress Plugins" page will not make [plinker] shortcode disappear.
		</p>
	</div>
	
	<div class="menu_toggle" style="background:<?php echo ptplGetColor(); ?>;">Select Your Menu To Show Related Posts</div>
	<div class="toggle_content" style="background:<?php echo ptplGetColor(); ?>;">
		<p>
			You can show this menu on your blog or keep it hidden from website, its upto you. But the menu will act as filtering out the related posts. How? Go through the below sections on this page to find out the working of plugin.<br/>
			All I can tell in brief is: (1) Add as many categories as you can for better results. Whenever any new category you add in categories, add the new one to the menu also. (2) Ordering is important for each category. To know how to re-order categories in menu for best results, read the plugin working section.
		</p>
		<p>
			Select your filtering menu :<br />
			<select name="selectedMenu">
<?php
	if( $ptplSelectedMenuID == "0" ){
		echo '<option value="0" selected="selected">Show Random Posts</option>';
	} else {
		echo '<option value="0">Show Random Posts</option>';
	}

	$menus = get_terms( 'nav_menu' );
	foreach( $menus as $menu ) :
		//echo "Name = ".$menu->name." ID = ".$menu->term_id."<br>";
		$menuID = $menu->term_id;
		$menuName = $menu->name;
		if( $menuID == $ptplSelectedMenuID ){
			echo '<option value="'.$menuID.'" selected="selected">'.$menuName.'</option>';
		} else {
			echo '<option value="'.$menuID.'">'.$menuName.'</option>';
		}
	endforeach;
?>			  			  
			</select> 
		</p>
	</div>
	
	<div class="menu_toggle" style="background:<?php echo ptplGetColor(); ?>;">Enter Your Default Headings</div>
	<div class="toggle_content" style="background:<?php echo ptplGetColor(); ?>;">
		<p>
			In this section you'll have to enter your default heading that will automatically be added to the posts. Checking the shuffle box will shuffle them while displaying on first visit of post. After than the headings will get permanent to that post.<br  />
			Enter one heading in per line. I suggest you should have four headings atleast.<br /><br />
			<textarea rows="5" cols="60" name="defaultHeadings"><?php echo $ptplDefaultHeadings; ?></textarea>
			<br />
			<?php
				if( $ptplShuffle == "yes" ){
			?>
					<input type="checkbox" checked="checked" name="shuffleHeadings" value="yes" > Shuffle Headings
			<?php
				} else {
			?>
					<input type="checkbox" name="shuffleHeadings" value="yes" > Shuffle Headings
			<?php
				}
			?>
			<br />
			Note:- To know how shuffle will work, see the working section of plugin.
			
		</p>
	</div>
	
	<div class="menu_toggle" style="background:<?php echo ptplGetColor(); ?>;">Save Your Settings Here</div>
	<div class="toggle_content" style="background:<?php echo ptplGetColor(); ?>;">
		<p>
			These change will be taken into consideration only for new posts. For the older ones you cannot modify now. Soon the update of this plugin will allow you to modify the older posts also.
		</p>
		<p>
			<button type="submit">Save Settings</button>
</form>
		</p>
	</div>
	
	<div class="menu_toggle" style="background:<?php echo ptplGetColor(); ?>;">How To Use Post Linker?</div>
	<div class="toggle_content" style="background:<?php echo ptplGetColor(); ?>;">
		<p>
			Using "Post Linker" is really very simple. What you've to do is just paste this code <code style="color:black;">[plinker]</code> in any of your article(s) and at any location and as many times you want to and no more 'and' in this sentence.<br />
			Using directly the shortcode <code style="color:black;">[plinker]</code> will take default settings which are: default post count is 5, default headings are taken from headings that are displayed above in headings section.
		</p>
		<h2>Options available with the code</h2>
		<p>
			You can set the number of related articles to show by using like this <code style="color:black;">[plinker count=3]</code>. This will show only 3 related posts instead of 5 which is default.<br />
<br />
			You can set the heading locally of the related post by using like this <code style="color:black;">[plinker heading='This is my special heading']</code>. This will show the heading for that section only. In any case, there was previous heading shown by heading attribute of code and you removed your heading locally then it will take up heading from default headings shown above.
		</p>
		<hr />
		<p>
			I've faced one problem, don't know why, that after updating any shortcode attribute, it doesn't reflect the changes. Like you've used <code style="color:black;">[plinker count=3 heading='My Special Heading']</code> and you changed it to <code style="color:black;">[plinker count=4 heading='New Heading']</code>, then changes will not reflect in post.<br />
<br />
			Found a workaround for it which is "Edit the post in which you've updated the post linker code, like add a dot (.) at the end of the article, update it and view changes."
		</p>
	</div>
	
	<div class="menu_toggle" style="background:<?php echo ptplGetColor(); ?>;">How Does Post Linker Works?</div>
	<div class="toggle_content" style="background:<?php echo ptplGetColor(); ?>;">
		<p>
			So you are at last here and actually want to know how "Post Linker" by <a href="http://pluginstalk.com" target="_blank">PluginsTalk</a> work, so that you can change the settings accurately. Firstly I would like to tell you that changing the settings frequently is not recommended from my side. Lets see the idea behind post linker now.
		</p>
		<h2>The Main Logic</h2>
		<p>
			Post Linker is used to insert automatically other related posts under the heading like "Recommended For You" or "You might alos like". Now you know what it does. I'll take an example of my website <a href="http://pluginstalk.com" target="_blank">PluginsTalk.com</a>. The website tell about the latest and coolest web browser plugins be it Firefox or Chrome or Safari or IE or Opera. You might also want to <a href="http://eepurl.com/uppg9" target="_blank">subscribe to keep yourself updated</a>.<br />
			So there are "<b>Broad Categories</b>" like "Firefox", "Chrome", etc. These categories are broad because be it any plugin it will fall under one of these categories. There are also "<b>Refined Categories</b>" like "Facebook", "Appearance", "Photos, Music & Videos", "Shopping", etc. These are refined in the sense that any plugin will fall under either one or some of the refined category and ofcourse in one of the broad category also.<br /><br />
			Lets suppose that instead of using "Post Linker" plugin you want to insert related posts manually. You are writing an article about a "photo related plugin", that is related to "Facebook", which will be installed in "Mozilla Firefox" and you want to insert the related posts manually.<br /><br />
			What will you do? Which are the best posts to be linked in this article?<br /><br />
			If the plugin is related to "Facebook" then its best to show more Facebook related plugin in related article, because it is more likely that the user is liking "Facebook plugins" and will be interested in more "Facebook plugins". This will keep the user busy enjoying your articles. Similarly you would also like to add "Photo related plugins" in this section as the plugin is photo related also. When you don't have any plugins to link then you pickup "Mozilla Firefox" plugins and show them because the plugin falls in "Mozilla Firefox" category also.<br />
			Notice the sequence: Facebook plugins > Photos plugins > Mozilla Firefox plugins > Random plugins. This is the sequence that the plugin takes as input from the menu. So order you categories in menu such that "<b>Refined Categories</b>" is above the "<b>Broader Categories</b>". Whenever you add new category add it to its relevant position.
		</p>
		<hr />
		<h2>What shuffle do to headings?</h2>
		<p>
			You've to insert shortcodes [plinker] wherever you want to see related articles in the posts/pages, you know this right?<br />
			Suppose you've long articles and want to insert the shortcode [plinker] four times in your articles. You don't want to see the headings sequence by "Post Linker" should be same in all the articles. Right?<br />
			If you've four to five headings in your default headings section and you want to show randomly show headings in your *new* articles then check the checkbox of shuffle headings. Or you may want to show all headings in same sequence inside every *new* articles then uncheck this checkbox.
		</p>
		<p>
			I've used *new* articles instead of all articles. The reason is explained at the top of this page which is "Post Linker doesn't change any <strong>headings</strong> or <strong>sequence of headings</strong> or <strong>sequence of related articles</strong> for any posts which are older and have Post Linker recommended articles in them generated."
		</p>
	</div>
<?php
	ptplShowLinkToUs ();
	ptplEndOutput ();
?> 